environment <- 'ENVIRONMENT' |> Sys.getenv()

expect.exist      <- \(component) component |> is.null() |> expect_equal(FALSE) 
expect.true       <- \(actual) actual |> expect_equal(TRUE)
expect.false      <- \(actual) actual |> expect_equal(FALSE)
expect.equal      <- \(component, expected) component |> expect_equal(expected)
expect.function   <- \(component) component |> is.function() |> expect_equal(TRUE)
expect.vector     <- \(component) component |> is.vector() |> expect_equal(TRUE)
expect.character  <- \(component) component |> is.character() |> expect_equal(TRUE)
expect.numeric    <- \(component) component |> is.numeric() |> expect_equal(TRUE)
expect.integer    <- \(component) component |> is.integer() |> expect_equal(TRUE)
expect.logical    <- \(component) component |> is.logical() |> expect_equal(TRUE)
expect.factor     <- \(component) component |> is.factor() |> expect_equal(TRUE)
expect.matrix     <- \(component) component |> is.matrix() |> expect_equal(TRUE)
expect.data.frame <- \(component) component |> is.data.frame() |> expect_equal(TRUE)
expect.rows       <- \(component, rows) component |> nrow() |> expect_equal(rows)
expect.list       <- \(members) members   |> is.list() |> expect_equal(TRUE)
expect.no.error   <- \(exception) exception |> expect_no_error()
expect.error      <- \(exception, error = NULL) exception |> expect_error(error)
expect.warning    <- \(actual, expected = NULL) actual |> expect_warning(expected)
